name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install necessary packages
        run: sudo apt install sqlite3 libsqlite3-dev python3-pip

      - name: Install Python packages
        run: sudo pip3 install pandas tabulate

      - name: Generate Materials HTML
        run: sudo python3 ./docs/additional_docs/gen_materials_page.py

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: "./docs/Doxyfile"
          working-directory: "."

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs/html
